gem 'twitter', '=4.8.1'
require 'tweetstream'
require 'twitter'
require 'time'
require 'yaml'
require 'mongo'
require 'mongo_mapper'
require 'date'
require 'hashie'
require 'pp'
require './models/user'
require './lib/twit_defs'
require './lib/def_methods'

